/**
 * Every word on the new screens, in Vietnamese (the default) and English. Wording follows the approved mockup
 * (docs/competition/mockup-v2); copy it lacked was written for these screens in both languages. Honesty words are
 * fixed: SIMULATED stays in English in both, the assistant "suggests" and "signals show", never "causes".
 */

const vi = {
  // shell
  navLabel: "Các màn",
  home: "Trang chủ", start: "Bắt đầu", desk: "Live Desk", recap: "Tổng kết", legacy: "Bản cũ",
  navDeskOff: "Chưa có live. Bắt đầu một buổi live ở màn Bắt đầu.",
  navRecapOff: "Tổng kết có sau khi bạn kết thúc live.",
  stamp: "SIMULATED Live",
  journey: "Hành trình dữ liệu",
  langLabel: "Ngôn ngữ",
  themeDark: "Giao diện tối", themeLight: "Giao diện sáng",
  keys: "Phím tắt", about: "Về dữ liệu này",
  close: "Đóng",
  modesLabel: "Chế độ của trợ lý",
  observe: "Quan sát", suggest: "Đề xuất", experiment: "Thí nghiệm",
  lockTitle: "Chế độ Thí nghiệm chưa mở",
  lockBody: "Bản này chưa có chế độ Thí nghiệm. Nó cần phiên từ 90 phút, đủ người xem và một thiết kế thử nghiệm đã duyệt. Vì vậy LiveLift không chạy thí nghiệm và không kết luận nhân quả.",
  lockOk: "Đã hiểu",
  live: "LIVE", viewersUnit: "người xem", unknown: "chưa rõ", paused: "Đang tạm dừng",
  endedAt: (t: string) => `Đã kết thúc lúc ${t}`,
  endLive: "Kết thúc live", seeRecap: "Xem tổng kết",
  // dock
  simData: "Dữ liệu mô phỏng",
  clockLabel: "Đồng hồ mô phỏng",
  run: "Chạy", pause: "Dừng", speedLabel: "Tốc độ đồng hồ", reset: "Đặt lại",
  speedNow: (v: number) => `Tốc độ ${v}×`, moreHint: ", tua nhanh và đặt lại", skipLabel: "Tua nhanh đồng hồ",
  skip: (s: number) => (s < 60 ? `+${s} giây` : `+${s / 60} phút`),
  fingerprint: "Vân tay lượt chạy", noFingerprint: "Chưa có sự kiện",
  // keys
  keysTitle: "Phím tắt",
  keyList: [
    ["Space", "Chạy hoặc dừng đồng hồ mô phỏng (Live Desk)"],
    ["1  2  3", "Bắt đầu, Live Desk, Tổng kết"],
    ["J", "Bật, tắt Hành trình dữ liệu"],
    ["↑  ↓", "Chọn bước khi Hành trình dữ liệu đang mở"],
    ["T", "Giao diện sáng hoặc tối"],
    ["P", "Chế độ trình chiếu: chữ to, ẩn thanh dưới"],
    ["?", "Danh sách phím này"],
    ["Esc", "Đóng lớp đang mở"],
  ] as [string, string][],
  // journey
  journeySub: "Sáu việc của đề tài Data Driven Business, và chỗ mỗi việc diễn ra trên Live Desk.",
  journeyHint: "Rê chuột hoặc bấm ↑ ↓ để xem từng bước.",
  journeyNoDesk: "Mở Live Desk của một buổi live để thấy bước này trên màn hình.",
  journeyClose: "Đóng hành trình dữ liệu",
  where: "Ở đâu",
  stageWord: "Bước",
  stages: [
    { title: "Thu thập", text: "Bình luận, người xem, thêm giỏ đổ về từng giây (mô phỏng).", where: "Khung Bình luận" },
    { title: "Làm sạch", text: "Che số điện thoại và email trước khi hiện và lưu.", where: "Dòng “đã che”, cuối khung Bình luận" },
    { title: "Phân tích", text: "Đếm ý định bình luận trong 2 phút qua.", where: "Năm ô đếm ý định" },
    { title: "Khai thác insight", text: "Biến số đếm thành lý do, kèm cỡ mẫu.", where: "Các con số và độ tin cậy" },
    { title: "Đề xuất giải pháp", text: "Nên ghim gì; người vận hành quyết định.", where: "Câu trả lời lớn ở giữa" },
    { title: "Đánh giá hiệu quả", text: "Nhận, bỏ qua, tự làm, và điều chưa biết.", where: "Nút Kết thúc live, mở Tổng kết" },
  ],
  // home
  homeTitle: "LiveLift đọc bình luận và giỏ hàng trong buổi live, rồi gợi ý bạn nên ghim gì, và vì sao.", homeTitleMark: "nên ghim gì",
  homeLede: "Bản này chạy trên SIMULATED Live trong trình duyệt của bạn: luật của trợ lý là thật, nền tảng và người xem là mô phỏng.",
  art: { recap: { kicker: "HẾT BUỔI" }, legacy: { kicker: "LƯU TRỮ", ruler: "CÁC MÀN TRƯỚC ĐÂY" } } as Record<"recap" | "legacy", { kicker: string; ruler?: string }>,
  heroSpec: {
    kicker: "MẪU MỘT GỢI Ý",
    simTag: "VÍ DỤ · SIMULATED",
    rows: [["Cỡ mẫu", "29 tín hiệu trong 2 phút"], ["Độ tin cậy", "Trung bình"], ["Nguồn", "Luật"], ["Trạng thái", "Gợi ý, chưa ghim"]] as [string, string][],
    ruler: "2 PHÚT GẦN NHẤT",
    fine: "Ví dụ để minh họa, không phải kết quả thật.",
  },
  flowLabel: "Bốn bước",
  flow: ["Kết nối", "Sản phẩm", "Bắt đầu live", "Live Desk"],
  flowDone: "Xong", flowNow: "Tiếp theo", flowLater: "Chưa tới",
  flowText: [
    "SIMULATED Live, một chạm.",
    "CSV hoặc bộ mẫu. Giá thiếu là thiếu, không phải 0.",
    "Bấm Chạy, rồi ghim tự do.",
    "Một gợi ý, kèm lý do và độ tin cậy.",
  ],
  statusLabel: "Trạng thái",
  connected: "Đã kết nối SIMULATED Live", notConnected: "Chưa kết nối",
  productsCount: (n: number, synced: number) => `${n} sản phẩm, ${synced} đã có trên SIMULATED`,
  liveRunning: (t: string) => `Một buổi live SIMULATED đang mở, đã chạy ${t}`,
  liveEnded: (t: string) => `Buổi live gần nhất đã kết thúc, dài ${t}`,
  nextLabel: "Bước tiếp theo",
  nextConnect: "Kết nối SIMULATED Live", nextImport: "Nhập sản phẩm của bạn", nextStart: "Bắt đầu buổi live",
  nextDesk: "Quay lại Live Desk", nextRecap: "Xem tổng kết buổi vừa rồi",
  openStart: "Mở màn Bắt đầu", openDesk: "Mở Live Desk", openRecap: "Mở Tổng kết",
  truthTitle: "Cái gì là thật, cái gì không",
  truth: [
    { term: "SIMULATED", text: "Nền tảng là SIMULATED Live: một nền tảng live mô phỏng nói chung, không phải của riêng nền tảng nào, chạy trong trình duyệt này. Không có gì được gửi tới hay nhận từ một nền tảng live thật nào." },
    { term: "Dữ liệu mô phỏng", text: "Người xem, bình luận, lượt thêm giỏ do bộ sinh dữ liệu tạo ra theo hạt giống cố định. Các giả định được liệt kê ở “Về dữ liệu này” trên Live Desk." },
    { term: "Chạy thật", text: "Luật gợi ý của trợ lý, việc che số điện thoại, phân loại ý định bình luận và mọi nút bạn bấm. Chúng chạy thật, trên dữ liệu mô phỏng." },
    { term: "Chưa có", text: "Kết nối nền tảng thật, cơ sở dữ liệu và chế độ Thí nghiệm. Buổi live chỉ được lưu trong trình duyệt này." },
  ],
  // start
  startTitle: "Chuẩn bị buổi live", startTitleLead: "Chuẩn bị", startTitleMark: "buổi live.",
  startLede: "Ba bước, chừng một phút. Sau đó LiveLift đọc bình luận và giỏ hàng để gợi ý bạn nên ghim gì, và vì sao.",
  simNote: "Nền tảng ở đây là một bản mô phỏng chạy ngay trong trình duyệt. Không có gì được gửi tới nền tảng live thật nào, và mọi con số là dữ liệu mô phỏng.",
  stepWord: "Bước", stepDone: "Đã xong", stepActive: "Đang làm", stepTodo: "Chưa tới",
  connectTitle: "Kết nối",
  connectBody: "LiveLift cần đọc bình luận, số người xem, lượt thêm giỏ, và gửi lệnh ghim sản phẩm.",
  connectBtn: "Kết nối SIMULATED Live",
  productsTitle: "Sản phẩm",
  productsSummary: (n: number, synced: number, missing: number) => `${n} sản phẩm, ${synced} đã có trên SIMULATED${missing ? `, ${missing} thiếu giá hoặc tồn kho` : ""}`,
  emptyProducts: "Chưa có sản phẩm nào",
  emptyProductsHelp: "Dán CSV hoặc TSV với bốn cột: mã, tên, giá, tồn kho. Hoặc dùng bộ sản phẩm mẫu để thử.",
  paste: "Dán CSV hoặc TSV",
  importBtn: "Nhập sản phẩm đã dán", sampleBtn: "Dùng bộ sản phẩm mẫu", addMore: "Nhập thêm sản phẩm",
  connectFirst: "Kết nối SIMULATED Live trước khi nhập.", pasteFirst: "Dán các dòng sản phẩm để nhập.",
  tableCaption: "Sản phẩm đã nhập và trạng thái trên SIMULATED Live",
  colProduct: "Sản phẩm", colPrice: "Giá", colStock: "Tồn kho", colStatus: "Trạng thái", colAction: "Thao tác",
  sync: { queued: "Đang chờ", synced: "Đã có trên SIMULATED", failed: "Không lên được" },
  platformSaid: "Nền tảng trả lời",
  missing: "Chưa nhập",
  remove: "Xóa",
  missingNote: (name: string, what: string) => `${name}: ${what} chưa nhập. LiveLift để trống, không coi là 0. Vẫn bắt đầu live được.`,
  missingWhat: (price: boolean, stock: boolean): string => (price && stock ? "giá và tồn kho" : price ? "giá" : "tồn kho"),
  startLiveTitle: "Bắt đầu live",
  startBody: "LiveLift bắt đầu đọc tín hiệu ngay khi bạn bấm; bạn vẫn ghim, bỏ ghim bất kỳ lúc nào. Đồng hồ mô phỏng đứng yên cho tới khi bạn bấm Chạy.",
  startBtn: "Bắt đầu live",
  startFailed: "Live chưa bắt đầu. Kiểm tra trạng thái nền tảng và thử lại.",
  // desk
  deskTitle: "Live Desk",
  notFound: "Không tìm thấy buổi live", notFoundHelp: "Trình duyệt này không có buổi live với mã đó. Bắt đầu một buổi live trước.",
  notStartedTitle: "Đồng hồ mô phỏng chưa chạy",
  products: "Sản phẩm", productsNote: "Ghim, bỏ ghim tự do",
  pin: "Ghim", unpin: "Bỏ ghim", pinning: "ĐANG GHIM",
  pinAria: (n: string) => `Ghim ${n}`, unpinAria: (n: string) => `Bỏ ghim ${n}`,
  suggestedChip: "Trợ lý gợi ý, chưa ghim",
  notOnPlatform: "Chưa có trên SIMULATED, không ghim được",
  priceStockMissing: "Giá, tồn kho chưa nhập", priceMissing: "Giá chưa nhập", stockMissing: "Tồn kho chưa nhập",
  stockLeft: (n: string) => `còn ${n}`,
  kicker: "Trợ lý đọc 2 phút gần nhất", kickerObserve: "Quan sát, 2 phút gần nhất", simDataTag: "dữ liệu SIMULATED",
  ledeNormal: "Tín hiệu 2 phút qua cho thấy người xem đang quan tâm nhiều đến sản phẩm này.",
  ledeLow: (n: number) => `Mới có ${n} tín hiệu. Tín hiệu cho thấy người xem bắt đầu quan tâm; cân nhắc trước khi ghim.`,
  ledeAi: "Câu này do mô hình AI viết lại; các con số bên dưới là của luật.",
  confidence: { low: "thấp", medium: "trung bình", high: "cao" },
  confidenceLine: (level: string) => `Độ tin cậy ${level}`,
  confidenceTail: (n: number) => `, cỡ mẫu ${n} tín hiệu trong 2 phút`,
  sourceLabel: "Nguồn", source: { rules: "luật", ai: "mô hình AI" },
  otherSignals: "Tín hiệu khác",
  acceptPin: (n: string) => `Ghim ${n}`, dismiss: "Bỏ qua",
  decide: "Bạn quyết định. Trợ lý không tự ghim.",
  waitingTitle: "Chưa đủ tín hiệu để gợi ý",
  waitingLede: (min: number) => `Trợ lý cần ít nhất ${min} tín hiệu (hỏi giá, hỏi cỡ, chốt đơn hoặc thêm giỏ) về cùng một sản phẩm chưa ghim trong 2 phút.`,
  idleTitle: "Bấm Chạy để bắt đầu",
  idleLede: "Đồng hồ mô phỏng đang đứng ở 00:00. Bấm Chạy (hoặc phím Space) để bình luận và người xem bắt đầu đổ về.",
  runSim: "Chạy mô phỏng",
  keepTitle: (n: string) => `Giữ ghim ${n}`,
  keepLede: (since: string | null) => `Chưa sản phẩm nào khác có đủ tín hiệu trong 2 phút qua.${since ? ` Đang ghim từ ${since}.` : ""}`,
  lastOutcome: "Gợi ý gần nhất",
  observeTitle: "2 phút qua, theo ý định bình luận",
  observeLede: "Chế độ Quan sát chỉ mô tả điều đã xảy ra. Trợ lý vẫn đọc tín hiệu nhưng không hiện gợi ý.",
  endedTitle: "Buổi live đã kết thúc",
  endedLede: "Các nút đã khoá. Mở Tổng kết để xem gợi ý nào được nhận, bỏ qua, tự làm, và điều chưa biết.",
  state: { proposed: "Đề xuất", accepted: "Đã nhận, chờ nền tảng hiện", dismissed: "Đã bỏ qua", performed: "Đã nhận, nền tảng đã hiện (SIMULATED)" },
  flashReadyTitle: "Nên chạy flash sale trong 1 phút",
  flashWhy: (name: string) => `Cho ${name}:`,
  flashRun: "Chạy flash sale",
  flashNotEnough: "Flash sale: chưa đủ tín hiệu.",
  flashNoPin: "Cần một sản phẩm đang ghim.",
  flashStockMissing: (n: string) => `Tồn kho ${n} chưa nhập; trợ lý không coi là đủ hàng.`,
  flashStockLow: (n: string, s: number, min: number) => `${n} chỉ còn ${s}, cần từ ${min}.`,
  flashRule: (min: number) => `Cần từ ${min} lượt thêm giỏ trong 2 phút cho sản phẩm đang ghim, nhiều hơn 2 phút trước đó.`,
  flashAccepted: (n: string) => `Flash sale cho ${n} đã được nhận và gửi lên lịch; chờ nền tảng bắt đầu (SIMULATED).`,
  flashPerformed: (n: string) => `Flash sale cho ${n}: nền tảng đã bắt đầu (SIMULATED Live).`,
  flashDismissed: "Flash sale: bạn đã bỏ qua gợi ý gần nhất.",
  flashObserve: "Flash sale: chế độ Quan sát không gợi ý.",
  chartTitle: "Người xem và thêm giỏ",
  seriesViewers: "Người xem cùng lúc", seriesCarts: "Lượt thêm giỏ mỗi phút, sản phẩm đang ghim",
  noShow: "Không ghim",
  chartNote: "Vạch dọc là lúc ghim hoặc bỏ ghim. Chúng cho biết khi nào, không chứng minh vì sao số thay đổi. Sọc chéo: không có sản phẩm đang ghim, không phải 0.",
  chartNoteShort: "Vạch dọc cho biết khi nào, không chứng minh vì sao.",
  markPin: (n: string) => `Ghim ${n}`, markUnpin: (n: string) => `Bỏ ghim ${n}`,
  markHostPin: (n: string) => `Người dẫn ghim ${n}`, markHostUnpin: (n: string) => `Người dẫn bỏ ghim ${n}`,
  chartEmpty: "Biểu đồ: chưa có dữ liệu. Bấm Chạy để bắt đầu.",
  chartSummary: (o: { span: string; first: string; last: string; peak: string; cartPeak: string; marks: string; noShow: number }) =>
    `Biểu đồ người xem và thêm giỏ, SIMULATED, trong ${o.span}: người xem từ ${o.first} đến ${o.last}, cao nhất ${o.peak}. Thêm giỏ mỗi phút của sản phẩm đang ghim cao nhất ${o.cartPeak}. ${o.marks}${o.noShow ? ` ${o.noShow} phút không có sản phẩm đang ghim, để trống.` : ""} Vạch đánh dấu cho biết khi nào, không cho biết vì sao.`,
  chartMarks: (list: string) => (list ? `Đánh dấu: ${list}.` : "Chưa ghim sản phẩm nào."),
  comments: "Bình luận",
  intentsLabel: "Ý định trong 2 phút",
  intentsGroup: "Ý định trong 2 phút qua; bấm một ô để lọc bình luận",
  intent: { ask_price: "Hỏi giá", ask_size: "Hỏi cỡ", ready_to_buy: "Chốt đơn", praise: "Khen", other: "Khác" },
  streamAll: "Bình luận mới nhất trước", streamFiltered: (i: string) => `Bình luận: ${i}`,
  masked: "đã che",
  noComments: "Chưa có bình luận.", noCommentsOfKind: "Chưa có bình luận thuộc loại này.",
  privacy: "Số điện thoại và email được che trước khi hiển thị và trước khi lưu.",
  privacyCount: (n: number) => (n ? `Đã che ${n} bình luận đang hiện.` : "Chưa có bình luận nào cần che."),
  phone: "Điện thoại người dẫn",
  phonePinned: "Đang ghim", phoneView: "Xem", phoneNoPin: "Chưa ghim sản phẩm", phoneEnded: "Buổi live đã kết thúc",
  phonePriceMissing: "Giá chưa nhập",
  phoneAria: (n: string | null) => (n ? `Xem trước điện thoại người dẫn: đang ghim ${n}` : "Xem trước điện thoại người dẫn: chưa ghim sản phẩm nào"),
  bannerHelp: "Nền tảng mô phỏng báo một lần. Gợi ý trên màn hình có thể đã cũ cho tới khi LiveLift đọc lại được.",
  endedNote: (t: string) => `Buổi live đã kết thúc lúc ${t}. Màn này chỉ để xem lại; các nút đã khoá.`,
  confirmTitle: (t: string) => `Kết thúc buổi live lúc ${t}?`,
  confirmBody: "LiveLift kết thúc buổi live trên SIMULATED Live, dừng đồng hồ mô phỏng và lập bản tổng kết. Không thể chạy tiếp buổi này.",
  confirmKeep: "Tiếp tục live", confirmEnd: "Kết thúc và xem tổng kết",
  // drawer
  aboutSim: "Cái gì là mô phỏng",
  aboutSimIntro: "Nền tảng là SIMULATED Live, chạy trong trình duyệt này. Không có gì được gửi tới nền tảng live thật nào. Bộ sinh dữ liệu dựa trên các giả định sau:",
  aboutRules: "Trợ lý gợi ý theo luật nào",
  aboutRuleList: (o: { min: number; rising: number; stock: number }) => [
    `Chỉ đọc 2 phút gần nhất. Gợi ý ghim một sản phẩm chưa ghim khi nó có từ ${o.min} tín hiệu: bình luận chốt đơn tính gấp đôi, hỏi giá, hỏi cỡ và thêm giỏ tính một.`,
    "Độ tin cậy chỉ dựa vào cỡ mẫu, không có phần trăm tự đặt: thấp dưới 10 tín hiệu, trung bình 10 đến 24, cao từ 25.",
    `Flash sale: gợi ý khi sản phẩm đang ghim có từ ${o.rising} lượt thêm giỏ trong 2 phút, nhiều hơn 2 phút trước đó, và tồn kho đã nhập từ ${o.stock}.`,
    "Trợ lý nói “tín hiệu cho thấy”, không nói nguyên nhân. Thêm giỏ không phải đơn hàng.",
    "Nhận một gợi ý là lựa chọn của bạn; “đã thực hiện” chỉ khi nền tảng mô phỏng cho thấy sản phẩm đang ghim hoặc flash sale đã bắt đầu.",
  ],
  aboutUnpin: "Lệnh bỏ ghim là suy đoán",
  aboutUnpinText: "Chỉ lệnh ghim (update_show_item) chép theo tài liệu tham khảo của Shopee. Lệnh bỏ ghim (unpin_show_item) là LiveLift đoán vì chưa tìm thấy trang tài liệu nào; các lệnh khác có hình dạng suy ra.",
  aboutPrivacy: "Thông tin cá nhân",
  aboutPrivacyText: "Số điện thoại và email trong bình luận được che trước khi hiển thị và trước khi lưu.",
  aboutRun: "Lượt chạy này",
  aboutRunText: "Cùng hạt giống, cùng sản phẩm và cùng các thao tác ở cùng giây luôn cho cùng vân tay, dù chạy nhanh, chậm hay nhảy giây.",
  aiStatus: "Trợ lý",
  aboutFault: "Diễn tập sự cố nền tảng",
  aboutFaultText: "Đặt SIMULATED Live vào một tình trạng để xem Live Desk xử lý thế nào. Sau khi bỏ sự cố, LiveLift đọc lại sau thao tác thành công tiếp theo của bạn.",
  fault: { token_expired: "Hết hạn quyền truy cập", rate_limited: "Giới hạn tần suất", server_error: "Lỗi máy chủ" },
  faultClear: "Bỏ sự cố", faultActive: "Đang diễn tập",
  aboutDesign: "Thiết kế so với thật",
  aboutDesignList: [
    "Buổi live chỉ được lưu trong trình duyệt này; bản có cơ sở dữ liệu là giai đoạn sau.",
    "Chế độ Thí nghiệm bị khoá: cần phiên từ 90 phút và một thiết kế thử nghiệm đã duyệt.",
  ],
  // recap
  recapTitle: "Tổng kết buổi live", recapTitleMark: "buổi live",
  recapMeta: (d: string) => `Buổi live mô phỏng, dài ${d}`,
  newLive: "Chuẩn bị buổi mới",
  recapNone: "Chưa có tổng kết", recapNoneHelp: "Tổng kết xuất hiện khi bạn kết thúc một buổi live.",
  recapRunning: "Buổi live chưa kết thúc", recapRunningHelp: "Kết thúc live trên Live Desk để lập tổng kết.",
  kpiPeak: "Người xem cao nhất", kpiPeakNote: (s: number) => `Lấy mẫu mỗi ${s} giây`,
  kpiCarts: "Thêm giỏ khi có ghim",
  kpiComments: "Bình luận Live Desk còn giữ",
  kpiCommentsNote: (from: string | null, masked: number) => `${from === null ? "" : `từ ${from}, `}đã che ${masked}`,
  decisionsSummary: (pins: string, taken: number, of: number) => `${pins} lần bạn ghim · nhận ${taken} trên ${of} gợi ý`,
  kpiOrders: "Đơn hàng", unknownBig: "Chưa biết",
  kpiOrdersNote: "Thêm giỏ không phải mua. Live Desk chưa nhận số đơn từ nền tảng.",
  timeline: "Diễn biến buổi live",
  timelineNote: "Nền màu là sản phẩm đang ghim. Sọc chéo là phút không có sản phẩm đang ghim.",
  unknowns: "Điều chưa biết",
  unknownCause: (n: string) => `Ghim ${n} có làm tăng thêm giỏ không?`,
  unknownCauseText: "Chưa biết. Thêm giỏ được đo khi sản phẩm đang ghim, không có nhóm đối chứng; quan sát không phải nhân quả. Muốn biết cần chế độ Thí nghiệm.",
  unknownOrders: "Số đơn hàng thật.", unknownOrdersText: "Chưa biết: thêm giỏ không phải mua, và Live Desk không nhận số đơn.",
  unknownComments: "Bình luận cả buổi.",
  unknownCommentsText: (from: string | null) => `Chưa biết: Live Desk chỉ giữ bình luận 5 phút gần nhất${from ? ` (từ ${from})` : ""}. Số ý định bên dưới là 2 phút cuối.`,
  unknownNoShow: (n: number) => `${n} phút không có sản phẩm đang ghim:`,
  unknownNoShowText: "thêm giỏ của “sản phẩm đang ghim” để trống, không tính là 0.",
  unknownMissingText: (what: string) => `${what} chưa nhập.`,
  decisions: "Gợi ý của trợ lý và bạn đã làm gì",
  colAt: "Lúc", colWhat: "Việc", colWhy: "Lý do trợ lý đưa ra", colYou: "Bạn",
  rowPin: (n: string) => `Ghim ${n}`, rowUnpin: (n: string) => `Bỏ ghim ${n}`, rowFlash: (n: string) => `Flash sale cho ${n}`,
  suggestedTag: "Gợi ý",
  why: (n: number, level: string, src: string) => `${n} tín hiệu, độ tin cậy ${level}, nguồn ${src}`,
  noWhy: "Không có gợi ý; bạn tự quyết", hostWhy: "Người dẫn thao tác trên ứng dụng; nền tảng ghi nhận (SIMULATED)",
  outcome: { open: "Còn mở", no_response: "Không phản hồi", accepted: "Nhận", performed: "Nhận", dismissed: "Bỏ qua", self: "Tự làm", host: "Người dẫn" },
  outcomeNote: { accepted: "chưa thấy trên nền tảng", performed: "nền tảng đã hiện" },
  noRows: "Không có gợi ý nào và bạn chưa ghim sản phẩm nào.",
  byIntent: "Bình luận theo ý định, 2 phút cuối",
  recapPrivacy: (masked: number, count: number) => `Đã che ${masked} trong ${count} bình luận Live Desk còn giữ.`,
  // legacy
  legacyTitle: "Bản cũ (Legacy)", legacyTitleMark: "Bản cũ",
  legacyIntro: "Các màn hình lập kế hoạch của bản V3 giữ nguyên đường dẫn và giao diện cũ.",
  legacyLinks: {
    oldHome: ["Trang chủ cũ", "Trang chủ trước đây: lên kế hoạch trước, từ Tạo đến Buổi sau."],
    sessions: ["Buổi live", "Các buổi đã lên kế hoạch, đang chạy và đã kết thúc của bản cũ."],
    products: ["Thư viện sản phẩm", "Thư viện sản phẩm của bản cũ."],
    insights: ["Phân tích", "Bằng chứng đã ghi nhận từ các buổi của bản cũ."],
    simulator: ["Trình mô phỏng", "Diễn tập các kịch bản lịch trình của bản cũ (SIMULATED)."],
    integrations: ["Tích hợp", "Khả năng nền tảng và cơ sở bằng chứng."],
    create: ["Lên kế hoạch buổi live (bản cũ)", "Thiết lập một buổi với lịch trình dự kiến, theo cách của bản cũ."],
  },
};

type Copy = typeof vi;

const en: Copy = {
  navLabel: "Screens",
  home: "Home", start: "Start", desk: "Live Desk", recap: "Recap", legacy: "Legacy",
  navDeskOff: "No live yet. Start one on the Start screen.",
  navRecapOff: "The recap appears after you end a live.",
  stamp: "SIMULATED Live",
  journey: "Data journey",
  langLabel: "Language",
  themeDark: "Dark theme", themeLight: "Light theme",
  keys: "Keys", about: "About this data",
  close: "Close",
  modesLabel: "Assistant mode",
  observe: "Observe", suggest: "Suggest", experiment: "Experiment",
  lockTitle: "Experiment mode is not open",
  lockBody: "This version has no Experiment mode. It needs sessions of 90 minutes or more, enough viewers and an approved test design. So LiveLift runs no experiment and draws no causal conclusion.",
  lockOk: "Got it",
  live: "LIVE", viewersUnit: "viewers", unknown: "unknown", paused: "Paused",
  endedAt: (t) => `Ended at ${t}`,
  endLive: "End live", seeRecap: "See recap",
  simData: "Simulated data",
  clockLabel: "Simulation clock",
  run: "Run", pause: "Pause", speedLabel: "Clock speed", reset: "Reset",
  speedNow: (v) => `Speed ${v}×`, moreHint: ", skip ahead and reset", skipLabel: "Skip the clock ahead",
  skip: (s) => (s < 60 ? `+${s} s` : `+${s / 60} min`),
  fingerprint: "Run fingerprint", noFingerprint: "No events yet",
  keysTitle: "Keys",
  keyList: [
    ["Space", "Run or pause the simulation clock (Live Desk)"],
    ["1  2  3", "Start, Live Desk, Recap"],
    ["J", "Show or hide the data journey"],
    ["↑  ↓", "Choose a stage while the data journey is open"],
    ["T", "Light or dark theme"],
    ["P", "Presenter mode: larger type, no bottom bar"],
    ["?", "This list"],
    ["Esc", "Close what is open"],
  ],
  journeySub: "The six steps of the Data Driven Business topic, and where each happens on the Live Desk.",
  journeyHint: "Hover or press ↑ ↓ to see each step.",
  journeyNoDesk: "Open the Live Desk of a live to see this step on screen.",
  journeyClose: "Close the data journey",
  where: "Where",
  stageWord: "Step",
  stages: [
    { title: "Collect", text: "Comments, viewers and add-to-carts arrive every second (simulated).", where: "The Comments column" },
    { title: "Clean", text: "Phone numbers and emails are masked before they are shown or stored.", where: "The “masked” line under Comments" },
    { title: "Analyse", text: "Comment intents are counted over the last 2 minutes.", where: "The five intent counters" },
    { title: "Find the insight", text: "Counts become reasons, with their sample size.", where: "The numbers and the confidence line" },
    { title: "Suggest", text: "What to pin next; the operator decides.", where: "The large answer in the middle" },
    { title: "Evaluate", text: "Accepted, dismissed, done yourself, and what is still unknown.", where: "The End live button, which opens the recap" },
  ],
  homeTitle: "LiveLift reads comments and carts during your live, then suggests what to pin next, and why.", homeTitleMark: "what to pin next",
  homeLede: "This version runs on SIMULATED Live in your browser: the assistant's rules are real, the platform and the viewers are simulated.",
  art: { recap: { kicker: "END OF SHOW" }, legacy: { kicker: "ARCHIVE", ruler: "EARLIER SCREENS" } },
  heroSpec: {
    kicker: "ANATOMY OF A SUGGESTION",
    simTag: "EXAMPLE · SIMULATED",
    rows: [["Sample size", "29 signals in 2 minutes"], ["Confidence", "Medium"], ["Source", "Rules"], ["State", "Suggested, not pinned"]] as [string, string][],
    ruler: "LAST 2 MINUTES",
    fine: "Illustration only, not a real result.",
  },
  flowLabel: "Four steps",
  flow: ["Connect", "Products", "Start live", "Live Desk"],
  flowDone: "Done", flowNow: "Next", flowLater: "Later",
  flowText: [
    "SIMULATED Live, one tap.",
    "A CSV or the sample pack. A missing price stays missing, never 0.",
    "Press Run, then pin freely.",
    "One suggestion, with its reasons and confidence.",
  ],
  statusLabel: "Status",
  connected: "Connected to SIMULATED Live", notConnected: "Not connected",
  productsCount: (n, synced) => `${n} products, ${synced} on SIMULATED`,
  liveRunning: (t) => `A SIMULATED live is open, running for ${t}`,
  liveEnded: (t) => `The last live has ended, after ${t}`,
  nextLabel: "Next step",
  nextConnect: "Connect the simulated platform", nextImport: "Import your products", nextStart: "Start a live rehearsal",
  nextDesk: "Back to the Live Desk", nextRecap: "See the recap of the last live",
  openStart: "Start", openDesk: "Open the Live Desk", openRecap: "Open the recap",
  truthTitle: "What is real, and what is not",
  truth: [
    { term: "SIMULATED", text: "The platform is SIMULATED Live: a simulated live-commerce platform in general, not any one real platform, running in this browser. Nothing is sent to or received from any real live platform." },
    { term: "Simulated data", text: "Viewers, comments and add-to-carts come from a seeded generator. Its assumptions are listed under “About this data” on the Live Desk." },
    { term: "Really running", text: "The assistant's rules, phone-number masking, comment intent classification and every button you press. They run for real, on simulated data." },
    { term: "Not yet", text: "A real platform link, a database and Experiment mode. The live is kept in this browser only." },
  ],
  startTitle: "Prepare the live", startTitleLead: "Prepare", startTitleMark: "the live.",
  startLede: "Three steps, about a minute. Then LiveLift reads comments and carts to suggest what to pin, and why.",
  simNote: "The platform here is a simulation running in your browser. Nothing is sent to any real live platform, and every number is simulated data.",
  stepWord: "Step", stepDone: "Done", stepActive: "In progress", stepTodo: "Not yet",
  connectTitle: "Connect",
  connectBody: "LiveLift needs to read comments, viewers and add-to-carts, and to send pin commands.",
  connectBtn: "Connect SIMULATED Live",
  productsTitle: "Products",
  productsSummary: (n, synced, missing) => `${n} products, ${synced} on SIMULATED${missing ? `, ${missing} missing a price or stock` : ""}`,
  emptyProducts: "No products yet",
  emptyProductsHelp: "Paste CSV or TSV with four columns: code, name, price, stock. Or try the sample pack.",
  paste: "Paste CSV or TSV",
  importBtn: "Import pasted products", sampleBtn: "Use sample pack", addMore: "Import more products",
  connectFirst: "Connect the simulated platform before importing.", pasteFirst: "Paste product rows to import.",
  tableCaption: "Imported products and their state on SIMULATED Live",
  colProduct: "Product", colPrice: "Price", colStock: "Stock", colStatus: "Status", colAction: "Action",
  sync: { queued: "Queued", synced: "On SIMULATED", failed: "Not accepted" },
  platformSaid: "The platform said",
  missing: "Not entered",
  remove: "Remove",
  missingNote: (name, what) => `${name}: ${what} not entered. LiveLift leaves it empty, never 0. You can still start the live.`,
  missingWhat: (price, stock) => (price && stock ? "price and stock" : price ? "price" : "stock"),
  startLiveTitle: "Start live",
  startBody: "LiveLift starts reading signals as soon as you press it; you can pin and unpin at any time. The simulation clock waits until you press Run.",
  startBtn: "Start live",
  startFailed: "Live did not start. Check platform status and try again.",
  deskTitle: "Live Desk",
  notFound: "Live not found", notFoundHelp: "This browser has no live with that id. Start a live first.",
  notStartedTitle: "The simulation clock is not running",
  products: "Products", productsNote: "Pin and unpin freely",
  pin: "Pin", unpin: "Unpin", pinning: "PINNED",
  pinAria: (n) => `Pin ${n}`, unpinAria: (n) => `Unpin ${n}`,
  suggestedChip: "Suggested, not pinned",
  notOnPlatform: "Not on SIMULATED, cannot be pinned",
  priceStockMissing: "Price, stock not entered", priceMissing: "Price not entered", stockMissing: "Stock not entered",
  stockLeft: (n) => `${n} left`,
  kicker: "The assistant reads the last 2 minutes", kickerObserve: "Observe, last 2 minutes", simDataTag: "SIMULATED data",
  ledeNormal: "Signals from the last 2 minutes show viewers paying attention to this product.",
  ledeLow: (n) => `Only ${n} signals so far. Signals show interest starting; think before you pin.`,
  ledeAi: "An AI model reworded this line; the numbers below are the rules'.",
  confidence: { low: "low", medium: "medium", high: "high" },
  confidenceLine: (level) => `Confidence ${level}`,
  confidenceTail: (n) => `, sample size ${n} signals in 2 minutes`,
  sourceLabel: "Source", source: { rules: "rules", ai: "AI model" },
  otherSignals: "Other signals",
  acceptPin: (n) => `Pin ${n}`, dismiss: "Dismiss",
  decide: "You decide. The assistant never pins on its own.",
  waitingTitle: "Not enough signals to suggest",
  waitingLede: (min) => `The assistant needs at least ${min} signals (ask price, ask size, ready to buy or add to cart) about one unpinned product in 2 minutes.`,
  idleTitle: "Press Run to begin",
  idleLede: "The simulation clock is at 00:00. Press Run (or Space) and comments and viewers start to arrive.",
  runSim: "Run the simulation",
  keepTitle: (n) => `Keep ${n} pinned`,
  keepLede: (since) => `No other product has enough signals in the last 2 minutes.${since ? ` Pinned since ${since}.` : ""}`,
  lastOutcome: "Last suggestion",
  observeTitle: "Last 2 minutes, by comment intent",
  observeLede: "Observe mode only describes what happened. The assistant still reads signals but shows no suggestion.",
  endedTitle: "This live has ended",
  endedLede: "Controls are locked. Open the recap to see what was accepted, dismissed, done yourself, and what is unknown.",
  state: { proposed: "Proposed", accepted: "Accepted, waiting for the platform", dismissed: "Dismissed", performed: "Accepted, the platform shows it (SIMULATED)" },
  flashReadyTitle: "Run a flash sale in the next minute",
  flashWhy: (name) => `For ${name}:`,
  flashRun: "Run flash sale",
  flashNotEnough: "Flash sale: not enough signals.",
  flashNoPin: "A product must be pinned.",
  flashStockMissing: (n) => `Stock of ${n} was not entered; the assistant does not treat it as enough.`,
  flashStockLow: (n, s, min) => `${n} has only ${s} left, needs ${min} or more.`,
  flashRule: (min) => `Needs ${min} or more add-to-carts in 2 minutes for the pinned product, more than the 2 minutes before.`,
  flashAccepted: (n) => `Flash sale for ${n} accepted and sent to be scheduled; waiting for the platform to start it (SIMULATED).`,
  flashPerformed: (n) => `Flash sale for ${n}: the platform has started it (SIMULATED Live).`,
  flashDismissed: "Flash sale: you dismissed the last suggestion.",
  flashObserve: "Flash sale: Observe mode makes no suggestion.",
  chartTitle: "Viewers and add-to-carts",
  seriesViewers: "Concurrent viewers", seriesCarts: "Add-to-carts per minute, pinned product",
  noShow: "Nothing pinned",
  chartNote: "Markers show when you acted, not what caused a change. Hatching: no product pinned, not zero.",
  chartNoteShort: "Markers show when, not why.",
  markPin: (n) => `Pin ${n}`, markUnpin: (n) => `Unpin ${n}`,
  markHostPin: (n) => `Host pinned ${n}`, markHostUnpin: (n) => `Host unpinned ${n}`,
  chartEmpty: "Chart: no data yet. Press Run to begin.",
  chartSummary: (o) =>
    `Viewers and add-to-carts, SIMULATED, over ${o.span}: viewers from ${o.first} to ${o.last}, highest ${o.peak}. Add-to-carts per minute for the pinned product peaked at ${o.cartPeak}. ${o.marks}${o.noShow ? ` ${o.noShow} minutes had nothing pinned and are left empty.` : ""} Markers show when, not why.`,
  chartMarks: (list) => (list ? `Markers: ${list}.` : "Nothing pinned yet."),
  comments: "Comments",
  intentsLabel: "Intents, last 2 minutes",
  intentsGroup: "Comment intents over the last 2 minutes; press one to filter the comments",
  intent: { ask_price: "Ask price", ask_size: "Ask size", ready_to_buy: "Ready to buy", praise: "Praise", other: "Other" },
  streamAll: "Comments, newest first", streamFiltered: (i) => `Comments: ${i}`,
  masked: "masked",
  noComments: "No comments yet.", noCommentsOfKind: "No comments of this kind yet.",
  privacy: "Phone numbers and emails are masked before they are shown or stored.",
  privacyCount: (n) => (n ? `${n} comments on screen were masked.` : "No comment has needed masking yet."),
  phone: "Host phone",
  phonePinned: "Pinned", phoneView: "View", phoneNoPin: "Nothing pinned", phoneEnded: "The live has ended",
  phonePriceMissing: "Price not entered",
  phoneAria: (n) => (n ? `Host phone preview: ${n} is pinned` : "Host phone preview: nothing pinned"),
  bannerHelp: "The simulated platform says this once. Suggestions on screen may be stale until LiveLift can read again.",
  endedNote: (t) => `The live ended at ${t}. This screen is for review only; controls are locked.`,
  confirmTitle: (t) => `End the live at ${t}?`,
  confirmBody: "LiveLift ends the live on SIMULATED Live, stops the simulation clock and builds the recap. This live cannot be resumed.",
  confirmKeep: "Keep going", confirmEnd: "End and see recap",
  aboutSim: "What is simulated",
  aboutSimIntro: "The platform is SIMULATED Live, running in this browser. Nothing is sent to any real live platform. The data generator rests on these assumptions:",
  aboutRules: "How the assistant suggests",
  aboutRuleList: (o) => [
    `It reads only the last 2 minutes. It suggests pinning an unpinned product with ${o.min} or more signals: ready-to-buy comments count twice, ask price, ask size and add-to-carts once.`,
    "Confidence comes from the sample size alone, never a made-up percentage: low under 10 signals, medium 10 to 24, high 25 or more.",
    `Flash sale: suggested when the pinned product has ${o.rising} or more add-to-carts in 2 minutes, more than the 2 minutes before, and entered stock of ${o.stock} or more.`,
    "The assistant says “signals show”, never a cause. An add-to-cart is not an order.",
    "Accepting is your choice; “performed” only when the simulated platform shows the pin or the started flash sale.",
  ],
  aboutUnpin: "Unpin is a guessed call",
  aboutUnpinText: "Only the pin call (update_show_item) copies Shopee's published reference. Unpin (unpin_show_item) is LiveLift's guess: no Shopee page was found for it. The other calls are shape inferred.",
  aboutPrivacy: "Personal data",
  aboutPrivacyText: "Phone numbers and emails in comments are masked before they are shown or stored.",
  aboutRun: "This run",
  aboutRunText: "The same seed, products and actions at the same seconds always give the same fingerprint, at any speed and with any skips.",
  aiStatus: "Assistant",
  aboutFault: "Rehearse a platform condition",
  aboutFaultText: "Put SIMULATED Live into a condition to see how the Live Desk handles it. After you clear it, LiveLift reads again after your next successful action.",
  fault: { token_expired: "Authorisation expired", rate_limited: "Rate limited", server_error: "Server error" },
  faultClear: "Clear condition", faultActive: "Rehearsing",
  aboutDesign: "Design versus reality",
  aboutDesignList: [
    "The live is kept in this browser only; a version with a database comes later.",
    "Experiment mode is locked: it needs sessions of 90 minutes or more and an approved test design.",
  ],
  recapTitle: "Live recap", recapTitleMark: "recap",
  recapMeta: (d) => `Simulated live, ${d} long`,
  newLive: "Prepare a new live",
  recapNone: "No recap yet", recapNoneHelp: "A recap appears when you end a live.",
  recapRunning: "The live has not ended", recapRunningHelp: "End the live on the Live Desk to build the recap.",
  kpiPeak: "Peak viewers", kpiPeakNote: (s) => `Sampled every ${s} s`,
  kpiCarts: "Add-to-carts while pinned",
  kpiComments: "Comments the Live Desk holds",
  kpiCommentsNote: (from, masked) => `${from === null ? "" : `from ${from}, `}${masked} masked`,
  decisionsSummary: (pins, taken, of) => `${pins} pins by you · ${taken} of ${of} suggestions accepted`,
  kpiOrders: "Orders", unknownBig: "Unknown",
  kpiOrdersNote: "An add-to-cart is not a purchase. The Live Desk receives no order count from the platform.",
  timeline: "How the live went",
  timelineNote: "Shading is the pinned product. Hatching marks minutes with nothing pinned.",
  unknowns: "What we do not know",
  unknownCause: (n) => `Did pinning ${n} raise add-to-carts?`,
  unknownCauseText: "Unknown. Add-to-carts were measured while it was pinned, with no comparison group; observation is not causation. Finding out needs Experiment mode.",
  unknownOrders: "Real orders.", unknownOrdersText: "Unknown: an add-to-cart is not a purchase, and the Live Desk receives no order count.",
  unknownComments: "Comments over the whole live.",
  unknownCommentsText: (from) => `Unknown: the Live Desk keeps only the last 5 minutes of comments${from ? ` (from ${from})` : ""}. The intent counts below are the last 2 minutes.`,
  unknownNoShow: (n) => `${n} minutes with nothing pinned:`,
  unknownNoShowText: "add-to-carts for “the pinned product” are left empty, not counted as 0.",
  unknownMissingText: (what) => `${what} not entered.`,
  decisions: "What the assistant suggested and what you did",
  colAt: "At", colWhat: "Action", colWhy: "The assistant's reason", colYou: "You",
  rowPin: (n) => `Pin ${n}`, rowUnpin: (n) => `Unpin ${n}`, rowFlash: (n) => `Flash sale for ${n}`,
  suggestedTag: "Suggested",
  why: (n, level, src) => `${n} signals, ${level} confidence, source ${src}`,
  noWhy: "No suggestion; your own call", hostWhy: "The host acted in the app; the platform recorded it (SIMULATED)",
  outcome: { open: "Open", no_response: "No response", accepted: "Accepted", performed: "Accepted", dismissed: "Dismissed", self: "Your own", host: "Host" },
  outcomeNote: { accepted: "not seen on the platform", performed: "the platform shows it" },
  noRows: "No suggestions, and you pinned nothing.",
  byIntent: "Comments by intent, last 2 minutes",
  recapPrivacy: (masked, count) => `${masked} of the ${count} comments the Live Desk still holds were masked.`,
  legacyTitle: "Legacy", legacyTitleMark: "Legacy",
  legacyIntro: "The V3 planning screens keep their original URLs and their original look.",
  legacyLinks: {
    oldHome: ["Original Home", "The earlier Home: the plan-first loop, Create to Next LIVE."],
    sessions: ["Sessions", "Browse the original planned, active and ended shows."],
    products: ["Product library", "Browse the original product library."],
    insights: ["Insights", "Review recorded evidence from the original shows."],
    simulator: ["Simulator", "Rehearse the original run-of-show scenarios (SIMULATED)."],
    integrations: ["Integrations", "See platform capabilities and their evidence basis."],
    create: ["Plan a show (original)", "Set up an original show with a planned run of show."],
  },
};

export const COPY = { vi, en } as const;
export type DeskCopy = Copy;
