import { describe, it, expect } from "vitest";
import {
  SCENARIOS,
  SCENARIO_START_MS,
  applyCommand,
  applyScriptStep,
  baselinePlan,
  buildReview,
  createScenarioSession,
  currentPlan,
  runScript,
  seedSimulatorSessions,
  skipScriptStep,
} from "@/lib/domain";

const T0 = SCENARIO_START_MS;
const at = (m: number, s = 0): number => T0 + (m * 60 + s) * 1000;

function finished(id: "buffered" | "missed" | "minimum") {
  const s = runScript(createScenarioSession(id));
  const review = buildReview(s);
  if (!review) throw new Error("expected an ended session");
  return { s, review };
}

describe("deterministic simulator", () => {
  it.each(SCENARIOS.map((x) => x.id))("scenario %s: same scenario + same actions = identical outcomes", (id) => {
    const a = runScript(createScenarioSession(id));
    const b = runScript(createScenarioSession(id));
    expect(JSON.stringify(a)).toBe(JSON.stringify(b));
    expect(a.lifecycle).toBe("ended");
  });

  it("a different action produces a different outcome", () => {
    // Both runs share the same scenario up to the host estimate at 20:07 (3 scripted steps).
    const shared = runScript(createScenarioSession("buffered"), 3);

    // Action X: the scripted decision (end Zip Hoodie by 20:12) then the scripted remainder.
    const x = runScript(shared);

    // Action Y: do nothing about it; the host runs to the estimate and the operator advances at 20:13.
    let y = skipScriptStep(shared); // skip the 'end by 20:12' decision
    const clock = applyCommand(y, { type: "set_clock", toMs: at(13), nowMs: 0 });
    y = clock.session;
    const adv = applyCommand(y, { type: "advance_segment", nowMs: 0 });
    expect(adv.receipt.outcome).toBe("committed");
    y = adv.session;

    const flashX = buildReview(x)!.rows.find((r) => r.title.startsWith("Flash"))!;
    expect(flashX.anchor?.status).toBe("on_time");

    const flashYStart = y.runtime.segments[`${y.id}:flash`].startedAtMs;
    expect(flashYStart).toBe(at(13)); // one minute after the 20:12 commitment
    expect(flashYStart).not.toBe(flashX.actual?.startMs);
  });

  it("applying a scripted step twice cannot double-apply it", () => {
    const s0 = createScenarioSession("buffered");
    const first = applyScriptStep(s0);
    expect(first.receipt?.outcome).toBe("committed");
    // Re-delivering the committed command key is a duplicate: same receipt, nothing re-applied.
    const dup = applyCommand(first.session, {
      type: "start_live",
      nowMs: 0,
      key: `${s0.id}:script:0`,
    });
    expect(dup.duplicate).toBe(true);
    expect(dup.receipt).toEqual(first.receipt);
    expect(dup.session.events.length).toBe(first.session.events.length);
    // Running the same step from the same start is reproducible.
    expect(JSON.stringify(applyScriptStep(s0).session)).toBe(JSON.stringify(first.session));
  });

  it("the seeded simulator sessions are SIMULATED, generated by the engine, and never REAL", () => {
    const seeds = seedSimulatorSessions();
    expect(seeds.length).toBe(4);
    expect(seeds.every((s) => s.environment === "SIMULATED")).toBe(true);
    const done = seeds.find((s) => s.lifecycle === "ended")!;
    expect(done.events.length).toBeGreaterThan(0);
    expect(done.events.every((e) => e.source === "simulator")).toBe(true);
    expect(JSON.stringify(seedSimulatorSessions())).toBe(JSON.stringify(seeds));
  });
});

describe("buffered recovery: Plan vs Actual", () => {
  it("compares this run to the immutable baseline", () => {
    const { s, review } = finished("buffered");
    const hoodie = review.rows.find((r) => r.title === "Zip Hoodie")!;
    expect(hoodie.baseline).toMatchObject({ startMs: at(3), endMs: at(9), durSec: 360 });
    expect(hoodie.actual).toMatchObject({ startMs: at(3), endMs: at(12), durSec: 540 });
    expect(hoodie.durationVarianceSec).toBe(180);
    expect(hoodie.overran).toBe(true);
    // The in-show revision exists, but the baseline target is untouched.
    expect(hoodie.baselineTargetSec).toBe(360);
    expect(hoodie.currentTargetSec).toBe(540);
    expect(hoodie.planChanges.length).toBeGreaterThan(0);
    expect(baselinePlan(s).segments.find((x) => x.title === "Zip Hoodie")!.targetSec).toBe(360);
    expect(currentPlan(s).segments.find((x) => x.title === "Zip Hoodie")!.targetSec).toBe(540);
  });

  it("the Flash Sale anchor was met on its committed time and the recovery decision is in the history", () => {
    const { review } = finished("buffered");
    const flash = review.rows.find((r) => r.title.startsWith("Flash"))!;
    expect(flash.anchor).toMatchObject({ committedMs: at(12), status: "on_time", lateBySec: 0, reAnchored: false });
    expect(review.history.some((h) => h.type === "recovery_selected")).toBe(true);
    expect(review.history.some((h) => h.type === "clock_advanced")).toBe(false);
    expect(review.summary.trackedSec).toBe(1800);
    expect(review.summary.anchors).toMatchObject({ total: 2, onTime: 2, late: 0 });
    expect(review.summary.cues).toMatchObject({ operatorTotal: 3, performed: 3, noReport: 0 });
  });

  it("every operator cue is a report with unknown platform verification", () => {
    const { review } = finished("buffered");
    const operatorCues = review.cues.filter((c) => c.audience === "operator");
    expect(operatorCues.every((c) => c.state === "performed" && c.verification === "unknown")).toBe(true);
    const presenter = review.cues.find((c) => c.audience === "presenter")!;
    expect(presenter.state).toBe("informational");
  });
});

describe("missed anchor: nothing is relabelled as recovered", () => {
  it("shows the anchor late against its unchanged baseline commitment", () => {
    const { review } = finished("missed");
    const flash = review.rows.find((r) => r.title.startsWith("Flash"))!;
    expect(flash.anchor).toMatchObject({ committedMs: at(12), currentCommittedMs: at(12), status: "late", lateBySec: 60, reAnchored: false });
    expect(flash.baseline?.startMs).toBe(at(12));
    expect(flash.actual?.startMs).toBe(at(13));
    expect(flash.startVarianceSec).toBe(60);
    expect(review.summary.anchors).toMatchObject({ late: 1, onTime: 1 });
  });

  it("the cue timed to the clock was reported late, not missed", () => {
    const { review } = finished("missed");
    const cue = review.cues.find((c) => c.title.startsWith("Activate"))!;
    expect(cue.state).toBe("performed");
    expect(cue.dueMs).toBe(at(12));
    expect(cue.lateBySec).toBe(90);
  });

  it("a skipped optional segment has no performed interval (missing != zero)", () => {
    const { review } = finished("missed");
    const qa = review.rows.find((r) => r.title === "Q&A")!;
    expect(qa.outcome).toBe("skipped");
    expect(qa.actual).toBeNull();
    expect(qa.durationVarianceSec).toBeNull();
    expect(qa.actualOrder).toBeNull();
    expect(review.summary.counts.skipped).toBe(1);
  });
});

describe("minimum exhaustion: re-anchor is a new commitment", () => {
  it("keeps the original 20:12 beside the new 20:16 and the miss against the original", () => {
    const { s, review } = finished("minimum");
    const flash = review.rows.find((r) => r.title.startsWith("Flash"))!;
    expect(flash.anchor).toMatchObject({ committedMs: at(12), currentCommittedMs: at(16), reAnchored: true, status: "late", lateBySec: 240 });
    expect(s.plans.length).toBeGreaterThan(1);
    expect(review.revisions.some((r) => r.reason?.includes("Re-anchored"))).toBe(true);
    expect(review.history.find((h) => h.type === "anchor_changed")?.summary).toContain("baseline commitment unchanged");
  });

  it("segments never reached are 'not reached', not zero-length", () => {
    // End the show early and look at what was never started.
    const partial = runScript(createScenarioSession("buffered"), 4);
    const ended = runScript(
      { ...partial, scriptCursor: 11 } // jump to the final scripted step: End LIVE
    );
    const review = buildReview(ended)!;
    const notReached = review.rows.filter((r) => r.outcome === "not_reached");
    expect(notReached.length).toBeGreaterThan(0);
    expect(notReached.every((r) => r.actual === null && r.durationVarianceSec === null)).toBe(true);
  });
});

describe("Plan vs Actual honesty", () => {
  it("'on plan' compares tracked time to the planned SPAN, not the sum of durations", () => {
    const { review } = finished("buffered");
    expect(review.summary.baselineHostSec).toBe(1620); // 27:00 of host time ...
    expect(review.summary.baselineSpanSec).toBe(1800); // ... plus a 3:00 idle buffer = 30:00 span
    expect(review.summary.trackedSec).toBe(1800);
    expect(review.summary.finishVarianceSec).toBe(0);
  });

  it("a skipped predecessor is not a reorder: ranks are among the segments that ran", () => {
    const { review } = finished("missed"); // Q&A skipped before Closing
    const closing = review.rows.find((r) => r.title === "Closing")!;
    expect(closing.actualOrder).toBe(closing.plannedRank);
    expect(review.rows.find((r) => r.title === "Q&A")!.actualOrder).toBeNull();
    expect(review.rows.find((r) => r.title === "Q&A")!.plannedRank).toBeNull();
  });

  it("a genuine reorder is recorded as one", () => {
    let s = runScript(createScenarioSession("buffered"), 6); // 20:12:10, Flash Sale running
    const step = (body: Parameters<typeof applyCommand>[1] extends infer C ? C : never): void => {
      const r = applyCommand(s, body);
      if (r.receipt.outcome !== "committed") throw new Error(`${body.type}: ${r.receipt.message}`);
      s = r.session;
    };
    const at2 = (m: number): number => SCENARIO_START_MS + m * 60_000;
    step({ type: "reorder_segment", segmentId: `${s.id}:qa`, beforeSegmentId: `${s.id}:b`, nowMs: 0 });
    step({ type: "set_clock", toMs: at2(15), nowMs: 0 });
    step({ type: "advance_segment", nowMs: 0 }); // Flash ends, Q&A starts
    step({ type: "set_clock", toMs: at2(18), nowMs: 0 });
    step({ type: "advance_segment", nowMs: 0 }); // Q&A ends, Cargo Pants starts
    step({ type: "set_clock", toMs: at2(26), nowMs: 0 });
    step({ type: "advance_segment", nowMs: 0 }); // Cargo Pants ends, Closing starts on its anchor
    step({ type: "set_clock", toMs: at2(30), nowMs: 0 });
    step({ type: "end_live", nowMs: 0 });
    const review = buildReview(s)!;
    const qa = review.rows.find((r) => r.title === "Q&A")!;
    const b = review.rows.find((r) => r.title === "Cargo Pants")!;
    expect([qa.actualOrder, qa.plannedRank]).toEqual([4, 5]);
    expect([b.actualOrder, b.plannedRank]).toEqual([5, 4]);
    expect(review.summary.counts.deferred).toBeGreaterThan(0);
  });
});
